version: '3'

tasks:
  deps:
    desc: Install system dependencies and swag
    cmds:
      - |
        if command -v apt-get > /dev/null; then
          echo "Using apt-get..."
          sudo apt-get update
          sudo apt-get install -y build-essential libpam-dev
        elif command -v dnf > /dev/null; then
          echo "Using dnf..."
          sudo dnf groupinstall -y "Development Tools"
          sudo dnf install -y pam-devel
        elif command -v yum > /dev/null; then
          echo "Using yum..."
          sudo yum groupinstall -y "Development Tools"
          sudo yum install -y pam-devel
        else
          echo "Unsupported package manager. Please install the dependencies manually."
          exit 1
        fi
      - go install github.com/swaggo/swag/cmd/swag@latest

  tidy:
    desc: Run go mod tidy
    cmds:
      - go mod tidy

  swag:
    desc: Generate Swagger docs
    cmds:
      - swag init -g cmd/server/main.go

  build:
    desc: Build the clab-api-server binary
    cmds:
      - go build -o clab-api-server ./cmd/server

  default:
    desc: Run all key steps (tidy, swag, build)
    cmds:
      - task tidy
      - task swag
      - task build
