name: Build and Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    #---------------------------------------------------------------
    # 1 — Checkout with full history (tags needed for git describe)
    #---------------------------------------------------------------
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    #---------------------------------------------------------------
    # 2 — Export build‑time metadata
    #---------------------------------------------------------------
    - name: Export build metadata
      run: |
        echo "VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo development)" >>"$GITHUB_ENV"
        echo "COMMIT=$(git rev-parse --short HEAD || echo unknown)" >>"$GITHUB_ENV"
        echo "DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >>"$GITHUB_ENV"

    #---------------------------------------------------------------
    # 3 — Install Go quickly
    #---------------------------------------------------------------
    - name: Setup Go (fast)
      uses: WillAbides/setup-go-faster@v1.14.0
      with:
        go-version: '1.21.x'

    #---------------------------------------------------------------
    # 4 — Fix mirrors, add arm64 repos, install cross tool‑chain
    #---------------------------------------------------------------
    - name: Configure apt and install cross tool‑chain
      run: |
        set -euxo pipefail

        # a) enable the architecture
        sudo dpkg --add-architecture arm64

        # b) swap flaky Azure mirror for canonical one
        sudo sed -Ei 's|http://azure\.archive\.ubuntu\.com/ubuntu|http://archive.ubuntu.com/ubuntu|g' /etc/apt/sources.list

        # c) restrict existing mirrors to amd64 only
        sudo sed -Ei 's/^deb /deb [arch=amd64] /' /etc/apt/sources.list

        # d) add ports.ubuntu.com as the arm64 mirror
        sudo tee /etc/apt/sources.list.d/arm64-ports.list <<'EOF'
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe multiverse
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-updates main restricted universe multiverse
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-security main restricted universe multiverse
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports jammy-backports main restricted universe multiverse
        EOF

        # e) refresh indices (retry on transient 404s)
        for i in {1..5}; do sudo apt-get update -qq && break || sleep 5; done

        # f) install cross compiler + headers
        for i in {1..5}; do \
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            gcc-aarch64-linux-gnu \
            linux-libc-dev:arm64 \
            libpam0g-dev:arm64 \
          && break || { sudo apt-get -y --fix-broken install || true; sleep 5; }; \
        done

        # g) sanity check
        dpkg -l gcc-aarch64-linux-gnu linux-libc-dev:arm64 libpam0g-dev:arm64

    #---------------------------------------------------------------
    # 5 — Cache Go modules / build cache
    #---------------------------------------------------------------
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    #---------------------------------------------------------------
    # 6 — Build linux/amd
