name: Build and Release

on:
  release:
    types: [created]

# Add permissions block to allow writing to releases
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get release tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Setup Go
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: '1.21'  # Adjust to your project's Go version
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpam-dev
      
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Build binary
        run: |
          go build -o clab-api-server cmd/server/main.go
          # Make binary executable
          chmod +x clab-api-server
      
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ./clab-api-server
      
      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: clab-api-server
          path: clab-api-server
          compression-level: 0