name: Build and Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Get release tag
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Setup Go (fast)
        uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: '1.21.x'

      # Host headers for CGO‑using tools (optional but safe)
      - name: Install PAM headers (host)
        run: |
          sudo apt-get update
          sudo apt-get install -y libpam0g-dev

      # Cache as before
      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      # Multi‑arch build (hooks/setup.sh installs PAM inside the container)
      - name: Build multi‑arch binaries
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: 1.21
          dest: dist
          prefix: clab-api-server
          pkg: ./cmd/server
          targets: linux/amd64,linux/arm64
          v: true
          ldflags: -s -w

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/clab-api-server-linux-amd64
            dist/clab-api-server-linux-arm64