name: Build and Release Binary

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-release:
    name: Build and Upload Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' 

      - name: Install build dependencies (amd64)
        if: ${{ matrix.goarch == 'amd64' }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential libpam0g-dev

      - name: Install build dependencies (arm64 cross)
        if: ${{ matrix.goarch == 'arm64' }}
        run: |
          # Add support for ARM64 packages
          sudo dpkg --add-architecture arm64
          sudo apt-get update -y
          # Install standard build tools, ARM64 cross-compiler, C libraries and PAM dev headers for ARM64
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu libc6-dev-arm64-cross libpam0g-dev:arm64

      - name: Build binary (${{ matrix.goos }}/${{ matrix.goarch }})
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
          # Use the ARM64 cross-compiler when building for arm64; default for amd64
          CC: ${{ matrix.goarch == 'arm64' && 'aarch64-linux-gnu-gcc' || '' }}
        run: |
          BINARY_NAME="clab-api-server-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}"
          echo "Building $BINARY_NAME..."
          go build -v -ldflags="-s -w" -o $BINARY_NAME ./cmd/server
          echo "Build complete: $BINARY_NAME"

      - name: Upload Release Asset (${{ matrix.goos }}/${{ matrix.goarch }})
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./clab-api-server-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_name: clab-api-server-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_content_type: application/octet-stream
