name: Build and Release (Debian container)

on:
  release:
    types: [created]

permissions:
  contents: write          # upload assets

jobs:
  build:
    runs-on: ubuntu-latest    # GitHub‑hosted VM
    container:
      image: debian:bookworm  # but every step runs in Debian 12
      options: --platform linux/amd64

    # --- use bash for every run step (fixes “Illegal option -o pipefail”) ---
    defaults:
      run:
        shell: bash

    steps:
      # 1 Checkout
      - uses: actions/checkout@v4

      # 2 Tag name for artefacts
      - id: tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >>"$GITHUB_OUTPUT"

      # 3 Install build dependencies
      - name: Install cross‑tool‑chains & PAM headers
        run: |
          set -euo pipefail
          # backports → Go 1.21
          echo "deb http://deb.debian.org/debian bookworm-backports main" \
            > /etc/apt/sources.list.d/backports.list            # 
          dpkg --add-architecture arm64                         # multi‑arch :contentReference[oaicite:2]{index=2}
          apt-get update -qq
          apt-get install -y --no-install-recommends \
            build-essential \
            gcc-aarch64-linux-gnu \                             # cross compiler :contentReference[oaicite:3]{index=3}
            libpam0g-dev libpam0g-dev:arm64 \                   # pam_appl.h (amd64+arm64) :contentReference[oaicite:4]{index=4}
            -t bookworm-backports golang-1.21-go                # Go 1.21 
          export PATH=$PATH:/usr/lib/go-1.21/bin                # expose go 

      # 4 Cache Go modules/build cache (works inside container)
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            /root/go/pkg/mod
            /root/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 5 Build linux/amd64 (native)
      - name: Build linux/amd64
        run: |
          set -euo pipefail
          mkdir -p dist
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 \
            go build -ldflags "-s -w" \
            -o dist/clab-api-server-linux-amd64 ./cmd/server

      # 6 Build linux/arm64 (cross)
      - name: Build linux/arm64
        env:
          CC: aarch64-linux-gnu-gcc
        run: |
          set -euo pipefail
          CGO_ENABLED=1 GOOS=linux GOARCH=arm64 \
            go build -ldflags "-s -w" \
            -o dist/clab-api-server-linux-arm64 ./cmd/server
          chmod +x dist/clab-api-server-linux-*

      # 7 Upload binaries to the Release
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/clab-api-server-linux-amd64
            dist/clab-api-server-linux-arm64

      # 8 Store artefacts
      - uses: actions/upload-artifact@v4
        with:
          name: clab-api-server-${{ steps.tag.outputs.TAG }}
          path: dist/
          retention-days: 7
